name: Godot 4 HTML5 Export

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Godot 4 editor
        run: |
          curl -L -o godot.zip https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux.x86_64.zip
          unzip -q godot.zip -d godot_bin
          echo "$(pwd)/godot_bin/Godot_v4.2.2-stable_linux.x86_64" > GODOT_BIN_PATH

      - name: Download Godot 4 export templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/4.2.2.stable
          curl -L -o templates.tpz https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_export_templates.tpz
          unzip -q templates.tpz -d ~/.local/share/godot/export_templates/4.2.2.stable

      - name: Export HTML5
        run: |
          BIN=$(cat GODOT_BIN_PATH)
          mkdir -p build/web
          "$BIN" --headless --export-release "Web" build/web/index.html

      - name: 404 fallback
        run: cp build/web/index.html build/web/404.html || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          force_orphan: true

