name: Godot 4 HTML5 Export (Self-healing Web preset)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  export:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.2.2   # Godot 4.2.2 + templates preinstalled
    steps:
      - name: Checkout (with LFS for audio)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Show repo tree
        run: |
          pwd
          ls -la
          echo "---- scenes/"; ls -la scenes || true
          echo "---- scripts/"; ls -la scripts || true

      # ✅ Force-create/overwrite export_presets.cfg with a 'Web' preset
      - name: Ensure Web export preset
        run: |
          cat > export_presets.cfg <<'EOF'
          [preset.0]
          name="Web"
          platform="Web"
          runnable=false
          dedicated_server=false
          export_filter="all_resources"
          export_path="build/web/index.html"

          [preset.0.options]
          custom_template/debug=""
          custom_template/release=""
          vram_texture_compression/bptc=true
          vram_texture_compression/s3tc=true
          vram_texture_compression/etc2=true
          vram_texture_compression/etc=false
          vram_texture_compression/no_bptc_fallbacks=false
          html/export_icon=true
          html/canvas_resize_policy=2
          html/focus_canvas_on_start=true
          binary_format/embed_pck=true
          EOF
          echo "==== export_presets.cfg written ===="
          sed -n '1,200p' export_presets.cfg

      # Sanity: project.godot must be at repo root
      - name: Verify project.godot exists at root
        run: |
          test -f project.godot || (echo "project.godot NOT found at repo root" && exit 1)
          echo "project.godot found ✅"

      - name: Godot version
        run: godot --version

      - name: Export HTML5 (verbose)
        run: |
          mkdir -p build/web
          godot --headless --verbose --export-release "Web" build/web/index.html

      - name: Create 404.html (SPA fallback)
        if: success()
        run: cp build/web/index.html build/web/404.html || true

      - name: Upload build artifact (for debugging if needed)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-build-or-logs
          path: |
            build/web
            .godot/**/*
            .import/**/*

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          force_orphan: true
