name: Godot 4 HTML5 Export

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export Web (uses GitHub-hosted binaries)
        uses: firebelley/godot-export@v6
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_64.zip
          export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_export_templates.tpz
          relative_project_path: .
          export_preset: "Web"
          output_path: build/web
          use_preset_name: true  # honors "Web" preset in export_presets.cfg
          cache: true            # speeds up next runs

      - name: Create 404.html (SPA fallback)
        run: cp build/web/index.html build/web/404.html || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          force_orphan: true
