name: Godot 4 HTML5 Export

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

env:
  PROJECT_DIR: .
  EXPORT_NAME: odysseus-web
  EXPORT_PRESET: Web

jobs:
  export:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.2.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify project.godot & ensure icon exists
        run: |
          set -euxo pipefail
          test -f "$PROJECT_DIR/project.godot" || { echo "project.godot NOT in $PROJECT_DIR"; exit 1; }
          sed -n '1,200p' "$PROJECT_DIR/project.godot" || true

          ICON=$(grep -E '^config/icon=' "$PROJECT_DIR/project.godot" | cut -d\" -f2 || true)
          echo "ICON=${ICON:-<none>}"
          if [[ -n "$ICON" ]]; then
            ICON_CLEAN="${ICON#res://}"
            ICON_PATH="$PROJECT_DIR/$ICON_CLEAN"
            if [[ ! -f "$ICON_PATH" ]]; then
              echo "⚠️ Icon '$ICON' missing. Creating placeholder at $ICON_PATH"
              mkdir -p "$(dirname "$ICON_PATH")"
              printf '%s\n' \
'<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128">' \
'  <rect width="100%" height="100%" fill="#1e1e2e"/>' \
'  <circle cx="64" cy="64" r="36" fill="#f59e0b"/>' \
'  <text x="64" y="72" font-size="20" text-anchor="middle" fill="#111">OD</text>' \
'</svg>' > "$ICON_PATH"
            fi
          fi

      - name: Verify export_presets.cfg exists
        run: |
          set -euxo pipefail
          if [[ ! -f "$PROJECT_DIR/export_presets.cfg" ]]; then
            echo "❌ Missing export_presets.cfg"
            exit 1
          fi
          grep -A3 "\[preset.*$EXPORT_PRESET" "$PROJECT_DIR/export_presets.cfg" || {
            echo "❌ Missing Web preset in export_presets.cfg"
            exit 1
          }

      - name: Export game (Web)
        run: |
          set -euxo pipefail
          mkdir -p build/web
          godot --headless --verbose --path "$PROJECT_DIR" --export-release "$EXPORT_PRESET" "build/web/index.html" || {
            echo "❌ Export failed"
            exit 1
          }

      - name: Upload web build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
