name: Godot 4 HTML5 Export (Diagnostic + Self-healing)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  export:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.2.2   # Godot 4.2.2 + HTML5 templates preinstalled

    steps:
      - name: Checkout (with LFS for audio)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Show repo tree
        run: |
          set -euxo pipefail
          pwd
          ls -la
          echo "---- scenes/"; ls -la scenes || true
          echo "---- scripts/"; ls -la scripts || true
          echo "---- audio/music"; ls -la audio/music || true

      # Ensure a valid Web preset exists (overwrites if present)
      - name: Ensure Web export preset
        run: |
          set -euxo pipefail
          cat > export_presets.cfg <<'EOF'
          [preset.0]
          name="Web"
          platform="Web"
          export_filter="all_resources"
          export_path="build/web/index.html"

          [preset.0.options]
          binary_format/embed_pck=true
          html/canvas_resize_policy=2
          EOF
          echo "==== export_presets.cfg ===="
          sed -n '1,200p' export_presets.cfg

      # Sanity: project.godot must be at repo root
      - name: Verify project.godot at root
        run: |
          set -euxo pipefail
          test -f project.godot || (echo "project.godot NOT found at repo root" && exit 1)
          echo "project.godot found ✅"
          echo "==== project.godot ===="
          sed -n '1,200p' project.godot || true

      # Optional: if an autoload path is wrong it can crash silently; comment it out temporarily
      - name: Temporarily disable AudioManager autoload if missing
        run: |
          set -euxo pipefail
          if ! [ -f scripts/AudioManager.gd ]; then
            awk 'BEGIN{p=1}/^\[autoload\]/{p=0} p{print} /^\[autoload\]/{print "; AudioManager=\"*res://scripts/AudioManager.gd\""}' project.godot > project.tmp
            mv project.tmp project.godot
            echo "⚠️ scripts/AudioManager.gd not found; autoload commented for this run."
          fi

      # Force Godot to import assets first (prevents export-time importer errors)
      - name: Godot version & pre-import
        run: |
          set -euxo pipefail
          godot --version
          # open headless editor once so .import/ is populated
          godot --headless -e --quit

      # Verify main scene exists where project.godot points
      - name: Check main scene exists
        run: |
          set -euxo pipefail
          MAIN=$(grep -E '^run/main_scene=' project.godot | cut -d\" -f2 | sed 's#^res://##')
          echo "Main scene from project.godot:" "$MAIN"
          test -f "$MAIN" || (echo "Main scene not found at $MAIN" && exit 1)

      # Export (verbose)
      - name: Export HTML5 (verbose)
        run: |
          set -euxo pipefail
          mkdir -p build/web
          godot --headless --verbose --export-release "Web" build/web/index.html

      # SPA 404 fallback
      - name: Create 404.html
        if: success()
        run: cp build/web/index.html build/web/404.html || true

      # Always upload artifacts so we can see logs even on failure
      - name: Upload build or logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-build-or-logs
          path: |
            build/web
            .godot/**/*
            .import/**/*
            export_presets.cfg
            project.godot

      # Deploy to Pages
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          force_orphan: true
