name: Godot Web Export (No external actions)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      # 2) Install Godot editor (4.2.2) from GitHub Releases
      - name: Install Godot editor
        run: |
          set -e
          GODOT_VER="4.2.2"
          mkdir -p "$HOME/godot_bin"
          wget -O /tmp/godot.zip "https://github.com/godotengine/godot/releases/download/${GODOT_VER}-stable/Godot_v${GODOT_VER}-stable_linux.x86_64.zip"
          unzip -q /tmp/godot.zip -d "$HOME/godot_bin"
          chmod +x "$HOME/godot_bin/Godot_v${GODOT_VER}-stable_linux.x86_64"
          echo "GODOT_BIN=$HOME/godot_bin/Godot_v${GODOT_VER}-stable_linux.x86_64" >> $GITHUB_ENV
          echo "Godot editor installed at: $HOME/godot_bin"

      # 3) Install HTML5 export templates
      - name: Install export templates (HTML5)
        run: |
          set -e
          GODOT_VER="4.2.2"
          DEST="$HOME/.local/share/godot/export_templates/${GODOT_VER}.stable"
          mkdir -p "$DEST"
          wget -O /tmp/templates.tpz "https://github.com/godotengine/godot/releases/download/${GODOT_VER}-stable/Godot_v${GODOT_VER}-stable_export_templates.tpz"
          mkdir -p /tmp/templates
          unzip -q /tmp/templates.tpz -d /tmp/templates
          # Move contents inside 'templates/' into expected directory
          mv /tmp/templates/templates/* "$DEST"/
          echo "Templates installed to: $DEST"

      # 4) Verify project.godot at repo root
      - name: Verify project at root
        run: |
          set -e
          test -f project.godot || { echo "project.godot NOT at repo root"; exit 1; }

      # 5) Write minimal Web preset (so export can't complain)
      - name: Write Web export preset
        run: |
          set -e
          cat > export_presets.cfg <<'EOF'
          [preset.0]
          name="Web"
          platform="Web"
          export_path="build/web/index.html"

          [preset.0.options]
          binary_format/embed_pck=true
          html/canvas_resize_policy=2
          EOF
          sed -n '1,120p' export_presets.cfg

      # 6) Ensure icon exists (placeholder if missing)
      - name: Ensure icon
        run: |
          set -e
          ICON=$(grep -E '^config/icon=' project.godot | cut -d\" -f2 || true)
          if [ -n "$ICON" ]; then
            REL=${ICON#res://}
            if [ ! -f "$REL" ]; then
              mkdir -p "$(dirname "$REL")"
              echo '<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128"><rect width="100%" height="100%" fill="#1e1e2e"/><circle cx="64" cy="64" r="36" fill="#f59e0b"/><text x="64" y="72" font-size="20" text-anchor="middle" fill="#111">OD</text></svg>' > "$REL"
            fi
          fi

      # 7) Check main scene actually exists
      - name: Check main scene
        run: |
          set -e
          MAIN=$(grep -E '^run/main_scene=' project.godot | cut -d\" -f2 | sed 's#^res://##')
          [ -n "$MAIN" ] || { echo "run/main_scene not set in project.godot"; exit 1; }
          [ -f "$MAIN" ] || { echo "Main scene not found at $MAIN"; exit 1; }

      # 8) Export HTML5 (with small retry to tolerate flakiness)
      - name: Export HTML5
        run: |
          set -e
          mkdir -p build/web
          for i in 1 2; do
            "$GODOT_BIN" --headless --export-release "Web" build/web/index.html && break || {
              echo "Export attempt $i failed; retrying in 10s..."; sleep 10;
            }
          done
          cp build/web/index.html build/web/404.html || true
          ls -la build/web || true

      # 9) Upload the build as an artifact
      - name: Upload web build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

      # 10) Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          force_orphan: true
